#:schema node_modules/wrangler/config-schema.json
name = "hono-cloudflare-workers-example"
main = "src/index.ts"
compatibility_date = "2024-05-02"
compatibility_flags = []

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "hono-cloudflare-workers-example"
database_id = "bc4f7a70-7c87-42cb-a9b9-d2eb528ac5da"
migrations_dir = "drizzle/migrations"
